all: skittles credit chart

skittles: skittles.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o skittles.bin skittles.c -lcc50 -lm
	
credit: credit.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o credit.bin credit.c -lcc50 -lm
	
chart: chart.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o chart.bin chart.c -lcc50 -lm
