all: skittles credit chart

skittles: skittles.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o skittles skittles.c -lcc50 -lm
	
credit: credit.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o credit credit.c -lcc50 -lm
	
chart: chart.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o chart chart.c -lcc50 -lm
